openapi: 3.0.0
info:
  title: Insurance API
  version: '1.0'
  description: かんたん自動お見積もりAPI
  contact:
    name: Fabien Deborde
    email: d-fabien@goldkey.co.jp
  license:
    name: MIT
servers:
  - url: 'https://asia-northeast1-apm-cloud-prod.cloudfunctions.net'
paths:
  /insurance_plan:
    get:
      summary: Get Plan
      tags: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      parameters:
        - schema:
            type: string
          in: query
          name: age
          required: true
          description: 世帯主の年齢
        - schema:
            type: string
          in: query
          name: adult_count
          required: true
          description: 世帯の構成：大人(満18歳以上)の人数
        - schema:
            type: string
          in: query
          name: kid_count
          required: true
          description: 世帯の構成：子供(満18歳未満)の人数
      description: Fetch the recommanded plan for given parameters.
      operationId: INSURANCE_PLAN
components:
  schemas: {}
